### ISSUE TITLE
Doesn't seem to work on MCPaper version 1.21.1

### ISSUE THREAD

**Issue by Haituga** [apexhosting/Scavenger-Hunt#2]
Unfortunately this plugin does not seem to work for Minecraft version 1.21.1.
I'm running it on the latest PaperMC build Paper 1.21.1 #76
Citizens2 and PlaceholderAPI are present and are up to date.

`[15:14:56 INFO]: [Scavenger] Enabling Scavenger v2.0
[15:14:56 ERROR]: Error occurred while enabling Scavenger v2.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'void net.citizensnpcs.trait.Gravity.gravitate(boolean)'
        at Scavenger.jar/dev.apexhosting.scavenger.entities.Game.<init>(Game.java:171) ~[Scavenger.jar:?]
        at Scavenger.jar/dev.apexhosting.scavenger.Scavenger.reload(Scavenger.java:78) ~[Scavenger.jar:?]
        at Scavenger.jar/dev.apexhosting.scavenger.Scavenger.onEnable(Scavenger.java:48) ~[Scavenger.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:1132) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.Bukkit.reload(Bukkit.java:1038) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:59) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
